blank_issues_enabled: false
contact_links:
  - name: Troubleshooting
    url:  https://github.com/aprilla/github-sandbox/blob/master/README.md#support
    about: checkout the README for troubleshooting directions
